
services:
  dash:
    command: python3 UI/main.py
    image: isratnipa/carpredictionthree:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 8050:80
    volumes:
      - .:/root/
      - ./.vscode-server:/root/.vscode-server