name: CICD for Car Price Prediction A3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve Project Repository
      uses: actions/checkout@v3


    - name: Set Up Python Runtime
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'


    - name: Install Project Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Unit Test Cases
      run: |
        pytest
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Clone Repository from GitHub
      uses: actions/checkout@v3

    - name: Authenticate with DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image for Deployment
      run: docker build -t isratnipa/carpredictionthree:latest .

    - name: Upload Image to DockerHub
      run: docker push isratnipa/carpredictionthree:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Remote Deployment via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{vars.HOST}}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{vars.PROXY_HOST}}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull isratnipa/carpredictionthree:latest
            docker compose -f st124984/docker-compose.yml down --remove-orphans
            docker compose -f st124984/docker-compose.yml up -d
          debug: true